name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # Adjust based on your PHP version
          tools: composer:v2

      - name: 📦 Install Composer Dependencies
        run: |
          cd docroot
          composer install --no-dev --optimize-autoloader

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./admin/ # Ensure this is correct
          server-dir: /public_html/website_6568a1f7/api # Adjust your deployment path
          exclude: |
            config.php
